name: Deploy to S3

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ca-central-1

      - name: Install AWS CLI
        run: sudo apt-get install -y awscli

      - name: Sync files to S3 bucket
        run: aws s3 sync . s3://febbucket-s3 --delete

      - name: Get S3 bucket URL
        id: s3_url
        run: echo "::set-output name=url::https://http://febbucket-s3.s3-website.ca-central-1.amazonaws.com"

      - name: Display S3 bucket URL
        run: echo "Static website URL:"http://febbucket-s3.s3-website.ca-central-1.amazonaws.com"
